### PR TITLE
adjust intervention countdown timer calculation to only use speaker times

### LINKED ISSUE #317: Intervention issues
**Describe the bug**
Time tracking for interventions and answers to interventions is no longer working correctly. When an intervention begins, it does not start at the set time but a few seconds earlier. Answers to interventions do not start at 0:00 but a few seconds later. The pattern is identical, just in the opposite direction.

The incorrect time tracking occurs in the projections of these speaking times (and sometimes in the list of speakers as well ). 

**How to Reproduce**
1. open a meeting with configured parliament mode (you can use our test data set for this)
2. open Autopilot and create an intervention. select a speaker. start it and take a look at the time. 
3. open the projector > create a new projector > activate 'Speaking times – overview structure levels' in projector  details
4. repeat start of intervention in autopilot and take a look at the time in the projection
5. do the same procedure for answers to interventions. 

**Expected behavior**
The set speaking time for interventions should be correctly displayed on the projector (and on the list of speakers.)

The speaking time for answers to an intervention should start correctly at 0:00 and be correctly displayed on the projector. 

**Additional context**
I'm not sure, but this issue can be a part of the reworked projector. If this is true, please feel free to transfer it to projector service.

Also I've added a label for staging. We have to fix this for the new release. 

I've first recognized this issue in the list of speakers in an existing meeting. There I could reproduce it. In a new meeting this happens only in the projection. - If you need further information contact me. 

**Important**: The time discrepancy occurs also for normal speeches. I guess it is a general problem. Please take account to this during debugging.

### PR DESCRIPTION
**Pull request by 4echow**
partially resolves #317 

This fix adjusts the intervention countdown timer calculation to only use speaker model time fields. This might help with some of the time discrepancy, but might be insufficient in regards to the different ways projector and client calculate their time values, as @bastianjoel mentioned in said issue.

### CODE REVIEW

**Review by bspekker — APPROVED** [review]
Works as intended.

**Review by peb-adr — APPROVED** [review]
LGTM

As discussed it might be sensible to compare how the client calculates the final countdown in (f.e.) the autopilot.

File: pkg/viewmodels/speaker.go [hunk 1]
```diff
@@ -35,11 +34,9 @@ func Speaker_CalculateInterventionCountdownTime(speaker *dsmodels.Speaker, inter
...
 
 	if speaker.PauseTime == 0 {
-		return float64(speaker.BeginTime) + float64(interventionTime) + float64(speaker.TotalPause)
+		return float64(interventionTime) + Speaker_CalculateElapsedTime(speaker)
 	} else {
-		now := int(time.Now().Unix())
-		elapsed := now - speaker.BeginTime - speaker.TotalPause
-		return float64(interventionTime) - float64(elapsed)
+		return float64(interventionTime) - Speaker_CalculateElapsedTime(speaker)
 	}
```
Comment (bastianjoel) [inline pkg/viewmodels/speaker.go:40]: The return values are the same. You do not need to do the check for pause time.

Comment (4echow) [reply pkg/viewmodels/speaker.go:40]: Look closer, one is addition, the other subtraction.
