### PR TITLE
`Motion-block` small changes

### LINKED ISSUE #153: Motion block
In general:
- font-weight from the numbers should be 500
- If recommendations are too long they are cut off wrong and are moved to the left (if they are too long theey should be ellipsed) ^1 and ^2
- the extension of recommendation is not visible

Short motion block:
- If a motion title is very long then the motion title pushed the recommendation and the title to the right (if they are too long theey should be ellipsed) ^2
- The Number should be more up (if a recommendation is activated then 

Looooong motion block: 
- Motion block (and single poll) was supposed to be scrollable to the right and not down/up. That's not yet implemented
- The distance from the Recommendation and the next Motion-number (right) should be a lot bigger
- The dictance between the recommmendation and the motion number (left) should be a bit bigger 

^1:
Image
^2
Image

### PR DESCRIPTION
**Pull request by Elblinator**
resolves #153

### CODE REVIEW

File: web/src/slide/projector_motion_block.js [hunk 1]
```diff
@@ -7,7 +7,8 @@ export class ProjectorMotionBlock extends HTMLElement {
 
   connectedCallback() {
     this.observer = new ResizeObserver(() => {
-      this.updateMotionNumberWidths();
+      this.updateWidth(this.querySelectorAll(`.motion-number`));
+      this.updateWidth(this.querySelectorAll(`.motion-detail`));
       this.updateGridColumnCount();
```
Comment (bastianjoel) [inline web/src/slide/projector_motion_block.js]: This is now unused as far as I can see.

**Comment by Elblinator** [comment]
I know that updateGridColumnCount() is now not called anymore
But I won't remove this here but in https://github.com/OpenSlides/openslides-projector-service/pull/172

#172 is dealing with the scroll and I want the least amount of merge conflicts and overhead work
