### PR TITLE
Fix countdowns css and overlapping behavior

### LINKED ISSUE #67: Fix projector countdown overlay
It is currently not possible to display multiple overlay countdowns. 

As the behavior of the current projector is not optimal a new solution should be developed.

### PR DESCRIPTION
**Pull request by 4echow**
resolves #67

### CODE REVIEW

File: web/src/projector.js [hunk 1]
```diff
@@ -90,29 +90,51 @@ export function Projector(host, id, auth = () => ``) {
   });
 
   eventSource.addEventListener(`projector-replace`, e => {
-    container.innerHTML = JSON.parse(e.data);
+    const html = JSON.parse(e.data);
+    container.innerHTML = html;
+
+    const projectorContainer = container.querySelector('#projector-container');
```
Comment (bastianjoel) [inline web/src/projector.js]: Slide specific logic should not be implemented here directly.

Implement this similar to the clock feature.

Comment (4echow) [reply web/src/projector.js]: moved specific logic to web/src/projector/overlay.js

File: templates/slides/projector_countdown.html [hunk 2]
```diff
@@ -1,6 +1,6 @@
 <link rel="stylesheet" type="text/css" href="/system/projector/static/slide/projector_countdown.css" />
-
-<div class="countdown {{ if .Options.Fullscreen }}fullscreen{{ else }}overlay{{ end }}">
+<!-- prettier-ignore -->
```
Comment (bastianjoel) [inline templates/slides/projector_countdown.html]: I would prefer not having to add this

File: templates/slides/projector_countdown.html [hunk 3]
```diff
@@ -1,6 +1,6 @@
...
+<div class="countdown {{ if .Options.Fullscreen }}fullscreen{{ else }}overlay{{ end }}" data-is-overlay="{{ if not .Options.Fullscreen }}true{{ else }}false{{ end }}">
```
Comment (bastianjoel) [inline templates/slides/projector_countdown.html]: You could just drop the attribute if the condition is not fulfilled instead of setting it to false

File: web/src/projector.css [hunk 4]
```diff
@@ -39,7 +39,7 @@ body {
   justify-content: space-between;
   position: relative;
   z-index: 10;
-  height: 70px;
+  height: 60px;
```
Comment (bastianjoel) [inline web/src/projector.css]: I don't see why this change has to be done

File: templates/slides/projector_countdown.html (hunk 2 above)
Comment (4echow) [reply templates/slides/projector_countdown.html]: the node linter formats the template in a way where the classes have newlines in the string, it breaks the javascript logic accessing them

File: web/src/projector.css (hunk 4 above)
Comment (4echow) [reply web/src/projector.css]: with 60px:
60px_timer
with 70px:
70px_timer

I don't know if maybe the issue was somewhere else, I just tried to make it look more similar.
